name: Import issues from CSV

on:
  workflow_dispatch:

jobs:
  import_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Import issues from CSV
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Bulk import issues
          content-filepath: ./Deliverables/issues.csv
          labels: Imported
